-- ============================================================================
-- MIGRATION v1.5: Autonomous Content Pipeline
-- Description: Adds raw_content_inbox and draft_articles tables for the
--              5-agent content pipeline (Harvester → Scout → Researcher →
--              Editor → Visualizer)
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 1. RAW CONTENT INBOX
--    Agent 1 (Harvester) writes here. Agent 2 (Scout) reads and scores.
-- ============================================================================
CREATE TABLE IF NOT EXISTS raw_content_inbox (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Source metadata
    source          VARCHAR(50) NOT NULL,       -- 'pubmed' | 'google_news' | 'ema'
    source_id       TEXT,                       -- External ID (PubMed PMID, etc.)
    source_url      TEXT,                       -- Original URL/link
    title           TEXT NOT NULL,
    abstract        TEXT,                       -- Raw content / snippet
    published_at    TIMESTAMPTZ,                -- Original publication date
    authors         TEXT[],                     -- Author names array
    raw_payload     JSONB DEFAULT '{}'::jsonb,  -- Full raw API response

    -- Scout scoring (filled by Agent 2)
    relevancy_score INTEGER,                    -- 1–100, NULL = not yet scored
    scout_output    JSONB,                      -- Full Scout JSON output
    scored_at       TIMESTAMPTZ,

    -- Pipeline state
    status          VARCHAR(30) NOT NULL DEFAULT 'pending',
    -- 'pending' | 'scored' | 'below_threshold' | 'promoted' | 'error'

    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_inbox_status          ON raw_content_inbox(status);
CREATE INDEX IF NOT EXISTS idx_inbox_source          ON raw_content_inbox(source);
CREATE INDEX IF NOT EXISTS idx_inbox_relevancy_score ON raw_content_inbox(relevancy_score DESC);
CREATE INDEX IF NOT EXISTS idx_inbox_created_at      ON raw_content_inbox(created_at DESC);
-- Prevent duplicate ingestion of the same external source article
CREATE UNIQUE INDEX IF NOT EXISTS idx_inbox_source_id_unique
    ON raw_content_inbox(source, source_id)
    WHERE source_id IS NOT NULL;

-- ============================================================================
-- 2. DRAFT ARTICLES
--    Promoted from inbox (score >= 75). Human reviews here before publishing.
-- ============================================================================
CREATE TABLE IF NOT EXISTS draft_articles (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    inbox_id        UUID REFERENCES raw_content_inbox(id) ON DELETE SET NULL,

    -- Core content
    slug            TEXT UNIQUE,                -- Generated by Editor, used in journal URL
    title           TEXT NOT NULL,
    body            TEXT,                       -- Danish markdown body (written by Editor)
    excerpt         TEXT,                       -- Short teaser (max ~300 chars)
    author          TEXT DEFAULT 'Redaktionen',

    -- Scout context (carried through pipeline)
    scout_output    JSONB,                      -- Full Scout JSON for downstream agents
    relevancy_score INTEGER,

    -- Researcher citations
    citations       JSONB DEFAULT '[]'::jsonb,  -- [{title, url, pmid}]

    -- Visualizer / Nano Banana
    hero_image_url  TEXT,                       -- Final Supabase Storage public URL
    image_prompt    TEXT,                       -- Prompt sent to Nano Banana

    -- Editorial workflow
    review_status   VARCHAR(30) NOT NULL DEFAULT 'pending_review',
    -- 'pending_review' | 'approved' | 'rejected' | 'published'
    reviewed_by     TEXT,
    reviewed_at     TIMESTAMPTZ,
    rejection_note  TEXT,

    -- Pipeline tracking
    pipeline_stage  VARCHAR(30) DEFAULT 'scout',
    -- 'scout' | 'researcher' | 'editor' | 'visualizer' | 'complete'

    tags            TEXT[] DEFAULT '{}',
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_drafts_review_status  ON draft_articles(review_status);
CREATE INDEX IF NOT EXISTS idx_drafts_pipeline_stage ON draft_articles(pipeline_stage);
CREATE INDEX IF NOT EXISTS idx_drafts_created_at     ON draft_articles(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_drafts_relevancy      ON draft_articles(relevancy_score DESC);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_draft_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_draft_updated_at ON draft_articles;
CREATE TRIGGER trg_draft_updated_at
    BEFORE UPDATE ON draft_articles
    FOR EACH ROW EXECUTE FUNCTION update_draft_updated_at();

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================
SELECT 'Migration v1.5 completed successfully' AS status;
